import { engine, Entity, AudioSource, Transform } from '@dcl/sdk/ecs'
import { Vector3 } from '@dcl/sdk/math'
import { GunId } from './weapon-profiles'

// Placeholder cues generated by asset-sources/weapons/generate_sounds.py (no Counter-Strike audio).
export type WeaponSound = 'reload' | 'knife_swing' | 'knife_hit' | 'dryfire' | `${GunId}_fire`
const WORLD_POOL = 6
const local = new Map<WeaponSound, Entity>()
const world: Entity[] = []
let nextWorld = 0

export function fireSound(gun: GunId): WeaponSound {
  return `${gun}_fire`
}

// Own weapon: follows the camera so it is always at full volume.
export function playLocalSound(name: WeaponSound) {
  let entity = local.get(name)
  if (entity === undefined) {
    entity = engine.addEntity()
    Transform.create(entity, { parent: engine.CameraEntity })
    local.set(name, entity)
  }
  AudioSource.playSound(entity, `assets/sounds/weapons/${name}.wav`, true)
}

// Other shooters: positional, from a small pool so bursts do not allocate entities.
export function playWorldSound(name: WeaponSound, position: Vector3) {
  if (world.length < WORLD_POOL) {
    const entity = engine.addEntity()
    Transform.create(entity, { position })
    world.push(entity)
  }
  const entity = world[nextWorld % world.length]
  nextWorld++
  Transform.getMutable(entity).position = position
  AudioSource.playSound(entity, `assets/sounds/weapons/${name}.wav`, true)
}
